# Generated by Django 5.1.3 on 2024-12-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_candidateapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='status',
            field=models.CharField(choices=[('selected', 'selected'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
