# Generated by Django 5.1.3 on 2024-12-01 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_candidateapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpost'),
        ),
    ]
