# Generated by Django 5.1.3 on 2024-12-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_candidateapplication_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='resume',
            field=models.FileField(upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('selected', 'selected')], default='pending', max_length=20),
        ),
    ]
